const fs = require("fs");
const path = require("path");
const express = require("express");
const routers = express.Router();
import gameRouter from "./gameRoute";
import quizRouter from "./quizRoute";
import questionRouter from "./questionRoute";
routers.use("/games", gameRouter);
routers.use("/quizzes", quizRouter);
routers.use("/questions", questionRouter);
export { routers };
